
# ISAM2 Solver Condition
/graphVIO/Use_ISAM2: True

# ISAM2 Parameters
ISAM2/params/relinearizeThreshold : 0.01
ISAM2/params/relinearizeSkip : 1
ISAM2/params/factorization: "CHOLESKY"


# IMU Parameters
/IMU/accel_noise_sigma: 0.0003924
/IMU/gyro_noise_sigma: 0.000205689024915
/IMU/accel_bias_rw_sigma: 0.000205689024915
/IMU/gyro_bias_rw_sigma: 0.000001454441043

# Other
/gravity: 9.80665





